# Generated by Django 5.0.4 on 2024-05-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='№ квартиры')),
                ('category', models.CharField(max_length=20, verbose_name='Объект')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('square', models.CharField(max_length=100, verbose_name='КВ')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('client', models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='Клиент')),
                ('status', models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='Статус')),
                ('client_number', models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='Номер клиента')),
                ('contract_number', models.IntegerField(blank=True, null=True, verbose_name='№ Договора')),
            ],
        ),
    ]
