# Generated by Django 5.0.4 on 2024-05-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flat',
            new_name='Apartment',
        ),
    ]
