# Generated by Django 5.0.4 on 2024-05-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_rename_flat_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='client_number',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='contract_number',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='number',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='square',
        ),
        migrations.AddField(
            model_name='apartment',
            name='object_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='square_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('активно', 'Активно'), ('бронь', 'Бронь'), ('куплено', 'Куплено'), ('рассрочка', 'Рассрочка'), ('бартер', 'Бартер')], default='active', max_length=20),
        ),
    ]
