# Generated by Django 5.0.4 on 2024-05-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_remove_apartment_category_remove_apartment_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('активно', 'Активно'), ('бронь', 'Бронь'), ('куплено', 'Куплено'), ('рассрочка', 'Рассрочка'), ('бартер', 'Бартер')], default='активно', max_length=20),
        ),
    ]
