# Generated by Django 5.0.4 on 2024-05-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_alter_apartment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='client_name',
            field=models.CharField(default='-', max_length=40),
        ),
        migrations.AddField(
            model_name='apartment',
            name='client_number',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
